### ISSUE TITLE
Root URL couldnt be found i guess

### ISSUE THREAD

**Issue by Thush8** [trustmaster/gkeep2notion#1]
Logging into Notion
Traceback (most recent call last):
  File "c:\Users\thush\Downloads\gkeep2notion-main\gkeep2notion.py", line 214, in <module>
    root = client.get_block(config.root_url)
  File "C:\Python310\lib\site-packages\notion\client.py", line 169, in get_block
    block = self.get_record_data("block", block_id, force_refresh=force_refresh)
  File "C:\Python310\lib\site-packages\notion\client.py", line 162, in get_record_data    
    return self._store.get(table, id, force_refresh=force_refresh)
  File "C:\Python310\lib\site-packages\notion\store.py", line 184, in get
    self.call_load_page_chunk(id)
  File "C:\Python310\lib\site-packages\notion\store.py", line 286, in call_load_page_chunk
    recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
  File "C:\Python310\lib\site-packages\notion\client.py", line 260, in post
    raise HTTPError(
requests.exceptions.HTTPError: Invalid input.

**Comment by stevenrabulan** [comment]
I'm getting a similar error as @Thush8 as well

**Comment by stevenrabulan** [comment]
No luck still. One thing I tried was obtaining a different token from a new browser session where I was only logged into my single workspace (instead of multiple). Same error

**Comment by stevenrabulan** [comment]
@Thush8 I just wanted to share my workaround that doesn't use the script with you. I don't mean to dismiss the work done by trustmaster on his script, but I needed to get my gkeep imported into notion ASAP so I couldn't hang around and wait for an answer. Thank you for your script @trustmaster 

I used https://takeout.google.com/settings/takeout/ to export my keep data ONLY. Then in notion, I used the import HTML feature. It creates a single page at the root of your notion that includes all of your imported notes. Before uploading, make sure to delete any HTML files that are > 5MB because notion will reject your import (images are sometimes embedded).
<img width="965" alt="Do Next 2022-08-07 at 4 42 32 PM" src="https://user-images.githubusercontent.com/4286112/183312049-ce063102-6a95-4436-aabe-dfe2cce79a6d.png">

**Comment by trustmaster** [comment]
I confirm the bug, I started getting this error myself. Seems like something has changed in the Notion API. I'll check it

**Comment by trustmaster** [comment]
So, the API update on the Notion side made the Python library that this script uses stop working. I'll need to rewrite this script to use a different Notion SDK library. Stay tuned for updates, and in the meantime you can use the Takeaway solution which is not so interactive but works.

**Comment by trustmaster** [comment]
I've updated the script to use a different Notion SDK, it should work again now. There are issues with formatting of messages, e.g. links are not formatted as links. I'll fix it later.
