### ISSUE TITLE
`notion_client.errors.APIResponseError: body failed validation`

### ISSUE THREAD

**Issue by Dentrax** [trustmaster/gkeep2notion#9]
I was following the README step by step and ended up the following error:

```
Traceback (most recent call last):
  File "/private/var/folders/nq/vxjjn3311fg4q263qsxrghpcpzgp66/T/tmp.H2EvgEH7/gkeep2notion/gkeep2notion.py", line 372, in <module>
    create_page(notion, notes)
  File "/private/var/folders/nq/vxjjn3311fg4q263qsxrghpcpzgp66/T/tmp.H2EvgEH7/gkeep2notion/gkeep2notion.py", line 168, in create_page
    notion_page = notion.pages.create(parent=page.parent,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/notion_client/api_endpoints.py", line 199, in create
    return self.parent.request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/notion_client/client.py", line 194, in request
    return self._parse_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/notion_client/client.py", line 126, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: body failed validation. Fix one:
body.parent.database_id should be defined, instead was `undefined`.
body.parent.page_id should be a valid uuid, instead was `""`.
```

**Comment by jenting** [comment]
I encountered the same issue as well.
It responds HTTP status 400 when trying the access the URL https://api.notion.com/v1/pages

```console
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://api.notion.com/v1/pages'
```

**Comment by trustmaster** [comment]
This is probably due to `notion-client` and Notion API upgrade. I've fixed the `notion-client` version to `1.0.0` for now and will work on `2.0` support later. Could you download the latest version and run `pip3 install -r requirements.txt` again?

**Comment by pulyankote** [comment]
> Could you download the latest version and run pip3 install -r requirements.txt again?

Same error even after downloading the latest version 
>  Requirement already satisfied: notion-client==1.0.0  (from -r requirements.txt (line 3)) (1.0.0)

**Comment by Hej-world** [comment]
It seems to work with some notes but I get the same error message for others. Trying to find out the difference between these notes in keep.

**Comment by StrictLine** [comment]
I already found out the root cause: url2uuid function which has the following RegEx condition for your link:
`^https://(www\.)?notion.so/(.+)([0-9a-f]{32})/?$`

I don't have the time to fix it right now, but you can workaround the bug by cutting of the query string from your URL that you got by clicking the 'Copy link' context menu action in Notion. In my case it was **?pvs=4**.

Important note: do NOT downgrade the notion-client, it simply upgraded it again, because it does not solve the URL conversion mistake. You can already see in your exception stack, that the id is missing:
`body.parent.database_id should be defined, instead was 'undefined'.
body.parent.page_id should be a valid uuid, instead was '""'.
`

As soon as you have a valid page_id the migration starts without any issues. If you are not familiar with the debugging in VSCode or with Python generally, put the following line after line 362 in `gkeep2notion.py`:
`print(f'root_uuid: {root_uuid}')`

If you see an empty output like `root_uid: ` upon starting the script, you definitely have the link in the wrong format according to the strict regex rule.

**Comment by trustmaster** [comment]
@StrictLine thanks for spotting the issue, the problem was in the `url2uuid` regex indeed. I've fixed it in the latest version.

**Comment by trustmaster** [comment]
Fixed
